// ══════════════════════════════════════════════════
//  DADOS COMPLETOS DAS CLASSES
// ══════════════════════════════════════════════════

const CLASSES = {
  bushi: {
    label: "Bushi", icon: "🛡️", img: "assets/images/classes/Bushi.png",
    desc: "Lutador rústico, baluarte da resistência e sobrevivência.",
    honra: "+0",
    nivel_inicial: { "Resolução":1,"Sucateiro":1,"Bateu Levou":2,"Movimento Rápido":2,"Talento de Sobrevivente":3,"Alvo Irresistível":4,"Esquiva Sobrenatural":5,"Fortificação":5,"Nem Morto":9,"Perto da Morte":10,"Hoje Não":14,"Fortificação Total":20 },
    pv_base: 24, pv_nivel: 6,
    pm_base: 4,  pm_nivel: 2,
    pericias_treinadas: "2 + modificador de Inteligência",
    pericias_classe: "Adestrar Animais (Car), Atletismo (For), Cavalgar (Des), Iniciativa (Des), Intimidação (Car), Ofício (Int), Percepção (Sab), Sobrevivência (Sab).",
    talentos_iniciais: "Usar Armaduras (leves, médias e pesadas), Usar Armas (simples e marciais), Fortitude Maior.",
    tabela: [
      { nivel:1,  bba:1,  hab:["Resolução (RD 2, 5 PV), sucateiro"] },
      { nivel:2,  bba:2,  hab:["Bateu levou, movimento rápido"] },
      { nivel:3,  bba:3,  hab:["Talento de sobrevivente"] },
      { nivel:4,  bba:4,  hab:["Alvo irresistível (−2)"] },
      { nivel:5,  bba:5,  hab:["Esquiva sobrenatural, fortificação (25%)"] },
      { nivel:6,  bba:6,  hab:["Talento de sobrevivente"] },
      { nivel:7,  bba:7,  hab:["Resolução (RD 5, 15 PV)"] },
      { nivel:8,  bba:8,  hab:["Esquiva sobrenatural aprimorada"] },
      { nivel:9,  bba:9,  hab:["Talento de sobrevivente, nem morto"] },
      { nivel:10, bba:10, hab:["Fortificação (50%), perto da morte (+4/+8)"] },
      { nivel:11, bba:11, hab:["Alvo irresistível (−4)"] },
      { nivel:12, bba:12, hab:["Talento de sobrevivente"] },
      { nivel:13, bba:13, hab:["Resolução (RD 10, 25 PV)"] },
      { nivel:14, bba:14, hab:["Hoje não"] },
      { nivel:15, bba:15, hab:["Fortificação (75%), talento de sobrevivente"] },
      { nivel:16, bba:16, hab:["Nem morto aprimorado"] },
      { nivel:17, bba:17, hab:["Perto da morte (+8/+16)"] },
      { nivel:18, bba:18, hab:["Talento de sobrevivente, alvo irresistível (−6)"] },
      { nivel:19, bba:19, hab:["Resolução (RD 15, 50 PV)"] },
      { nivel:20, bba:20, hab:["Fortificação total"] },
    ],
    habilidades: {
      "Resolução": "Por amor à vida, força de vontade, o bushi tolera ferimentos que matariam qualquer outra criatura. Usar esta habilidade é uma ação livre: você recebe redução de dano 2 e 5 pontos de vida temporários. Consome 1 PM e dura uma cena. Evolui para RD 5/15 PV no 7º, RD 10/25 PV no 13º e RD 15/50 PV no 19º nível.",
      "Sucateiro": "Pode comprar qualquer item mundano (não obra-prima ou mágico) por metade do preço padrão. Usar um item sucateado é violação de honra leve.",
      "Bateu Levou": "A partir do 2º nível, ao receber um ataque corpo-a-corpo, você pode gastar 1 PM para realizar um ataque corpo-a-corpo contra o mesmo oponente como reação.",
      "Movimento Rápido": "No 2º nível, seu deslocamento aumenta em +3m.",
      "Talento de Sobrevivente": "No 3º nível, e a cada 3 níveis seguintes, você ganha um talento entre: Autossuficiente, Casca Grossa, Corrida, Duro de Matar, Fortitude Maior, Perícia Aprimorada (Atletismo, Percepção ou Sobrevivência), Rastrear, Reflexos Rápidos, Tolerância, Violência Velada, Vitalidade, Vontade de Ferro.",
      "Alvo Irresistível": "A partir do 4º nível, você atrai os ataques inimigos para si. Um oponente que consiga percebê-lo sofre −2 em ataques contra seus nakama (mas não contra você). Aumenta para −4 no 11º e −6 no 18º nível.",
      "Esquiva Sobrenatural": "No 5º nível, nunca fica surpreendido. No 8º nível, aprimorada: pode lutar contra múltiplos inimigos sem ser flanqueado.",
      "Fortificação": "No 5º nível, 25% de chance de ignorar dano adicional de acerto crítico ou ataque furtivo. Aumenta para 50% no 10º, 75% no 15º e total (imunidade) no 20º nível.",
      "Nem Morto": "No 9º nível, se for reduzido a 0 PV enquanto em resolução, mantém-se consciente e age normalmente (ainda deve fazer testes de Constituição para não sangrar). No 16º nível aprimorado: só morre se PV negativos igualarem seus PV totais.",
      "Perto da Morte": "A partir do 10º nível, com menos da metade dos PV totais, recebe +4 nas jogadas de ataque e dano. Dobrado com 10 PV ou menos. No 17º nível, aumenta para +8 (dobrado com 20 PV ou menos).",
      "Hoje Não": "A partir do 14º nível, ao falhar em teste de resistência, você pode pagar 2 PM para repetir e ficar com o novo resultado, mesmo sendo pior.",
      "Fortificação Total": "No 20º nível, você é imune a acertos críticos e ataques furtivos.",
    }
  },

  kensei: {
    label: "Kensei", icon: "⚔️", img: "assets/images/classes/Kensei.png",
    desc: "Guerreiro devotado ao domínio de uma única arma.",
    honra: "+0",
    nivel_inicial: { "Arma Eleita":1,"Dano Desarmado":1,"Técnica de Luta":1,"Poder Marcial":2,"Aprendiz de Golpes":3,"Versado em Arma":3,"Golpe Extra":5,"Meditação":6,"Arma Polivalente":7,"Arma Querida":10,"Arma Indestrutível":14,"Golpe Mortal":16 },
    pv_base: 20, pv_nivel: 5,
    pm_base: 5,  pm_nivel: 3,
    pericias_treinadas: "2 + modificador de Inteligência",
    pericias_classe: "Acrobacia (Des), Atletismo (For), Cavalgar (Des), Iniciativa (Des), Intimidação (Car), Intuição (Sab), Ofício (Int), Percepção (Sab).",
    talentos_iniciais: "Usar Armaduras (leves e médias), Usar Armas (simples e marciais), Foco em Arma, Reflexos Rápidos.",
    tabela: [
      { nivel:1,  bba:1,  hab:["Arma eleita, dano desarmado (1d6), técnica de luta"] },
      { nivel:2,  bba:2,  hab:["Poder marcial +2"] },
      { nivel:3,  bba:3,  hab:["Aprendiz de golpes, versado em arma +2"] },
      { nivel:4,  bba:4,  hab:["Dano desarmado (1d8), técnica de luta"] },
      { nivel:5,  bba:5,  hab:["Golpe extra"] },
      { nivel:6,  bba:6,  hab:["Meditação (2 horas)"] },
      { nivel:7,  bba:7,  hab:["Arma polivalente"] },
      { nivel:8,  bba:8,  hab:["Dano desarmado (1d10), técnica de luta"] },
      { nivel:9,  bba:9,  hab:["Versado em arma +4"] },
      { nivel:10, bba:10, hab:["Arma querida"] },
      { nivel:11, bba:11, hab:["Meditação (1 hora)"] },
      { nivel:12, bba:12, hab:["Dano desarmado (2d6), técnica de luta"] },
      { nivel:13, bba:13, hab:["Poder marcial +4"] },
      { nivel:14, bba:14, hab:["Arma indestrutível"] },
      { nivel:15, bba:15, hab:["Versado em arma +6"] },
      { nivel:16, bba:16, hab:["Dano desarmado (2d8), golpe mortal (20 natural), técnica de luta"] },
      { nivel:17, bba:17, hab:["Meditação (30 minutos)"] },
      { nivel:18, bba:18, hab:["Golpe mortal (crítico)"] },
      { nivel:19, bba:19, hab:["Versado em arma +8"] },
      { nivel:20, bba:20, hab:["Dano desarmado (2d10), golpe mortal (rolagem única), técnica de luta"] },
    ],
    habilidades: {
      "Arma Eleita": "No 1º nível, recebe Foco em Arma para sua arma escolhida e uma versão obra-prima dela gratuitamente. Suas habilidades só funcionam com armas do mesmo tipo.",
      "Dano Desarmado": "Se escolheu ataque desarmado, seu dano aumenta progressivamente: 1d6 (1º), 1d8 (4º), 1d10 (8º), 2d6 (12º), 2d8 (16º), 2d10 (20º).",
      "Técnica de Luta": "No 1º nível, recebe um talento de combate. No 4º nível, e a cada 4 níveis seguintes, recebe outro talento de combate.",
      "Poder Marcial": "A partir do 2º nível, ao atacar com a arma eleita, pode gastar 1 PM (ação livre) para +2 no ataque ou dano. Pode gastar mais PM distribuindo como quiser (máximo igual ao seu nível). No 12º nível, para cada 1 PM gasto, recebe +4.",
      "Aprendiz de Golpes": "No 3º nível, pode escolher o talento Conhecimento de Jutsus para aprender jutsus com 'golpe' ou 'arma' no nome. Não resulta em violação de honra.",
      "Versado em Arma": "No 3º nível, +2 em testes de perícia ligados a armas do mesmo tipo da arma eleita. Aumenta para +4 no 9º, +6 no 15º e +8 no 19º nível.",
      "Golpe Extra": "No 5º nível, pode gastar 2 PM para realizar um ataque extra com o mesmo modificador de ataque.",
      "Meditação": "No 6º nível, para cada 2 horas de meditação, recupera 2 PV e 1 PM por nível. +5 no próximo teste de Fortitude. Reduz para 1 hora no 11º e 30 minutos no 17º.",
      "Arma Polivalente": "No 7º nível, pode executar o jutsu Arma de Dai'Gun pelo custo normal, mesmo sem chacras abertos, usando sua arma eleita.",
      "Arma Querida": "No 10º nível, recebe +4 em jogadas de ataque para evitar manobras de desarmar e separar, e +8 em Percepção para evitar roubo.",
      "Arma Indestrutível": "No 14º nível, ao empunhar a arma eleita, sua RD é dobrada e seus PV são iguais à metade dos PV totais do kensei.",
      "Golpe Mortal": "No 16º nível, ao rolar um 20 natural com a arma eleita, pode fazer uma segunda rolagem; se acertar, o multiplicador de crítico aumenta em +2. No 18º nível, ativa com qualquer crítico. No 20º nível, não precisa de segunda rolagem.",
    }
  },

  monge: {
    label: "Monge", icon: "👊", img: "assets/images/classes/Monge.png",
    desc: "Artista marcial, senhor do combate desarmado e técnicas secretas.",
    honra: "+1",
    nivel_inicial: { "Dano Desarmado":1,"Rajada de Golpes":1,"Sexto Sentido":1,"Técnica de Luta":1,"Evasão":2,"Movimento Rápido":3,"Ataque Chi":4,"Movimento Ágil":4,"Meditação":5,"Integridade Corporal":7,"Aperfeiçoamento":11,"Autoperfeição":20 },
    pv_base: 16, pv_nivel: 4,
    pm_base: 5,  pm_nivel: 3,
    pericias_treinadas: "4 + modificador de Inteligência",
    pericias_classe: "Acrobacia (Des), Atletismo (For), Conhecimento (Int), Cura (Sab), Diplomacia (Car), Furtividade (Des), Iniciativa (Des), Intuição (Sab), Ofício (Int), Percepção (Sab).",
    talentos_iniciais: "Usar Armas (simples), Usar Armas Exóticas (escolha três armas de monge), Fortitude Maior, Reflexos Rápidos, Vontade de Ferro, Ataque Desarmado Aprimorado.",
    tabela: [
      { nivel:1,  bba:1,  hab:["Dano desarmado (1d6), rajada de golpes, sexto sentido, técnica de luta"] },
      { nivel:2,  bba:2,  hab:["Evasão, técnica de luta"] },
      { nivel:3,  bba:3,  hab:["Movimento rápido +3m"] },
      { nivel:4,  bba:4,  hab:["Ataque chi (RD 5), dano desarmado (1d8), movimento ágil +5"] },
      { nivel:5,  bba:5,  hab:["Meditação (2 horas), sexto sentido +1"] },
      { nivel:6,  bba:6,  hab:["Movimento rápido +6m, técnica de luta"] },
      { nivel:7,  bba:7,  hab:["Integridade corporal"] },
      { nivel:8,  bba:8,  hab:["Dano desarmado (1d10)"] },
      { nivel:9,  bba:9,  hab:["Evasão aprimorada, movimento ágil +10, movimento rápido +9m"] },
      { nivel:10, bba:10, hab:["Ataque chi (RD 10), sexto sentido +2, técnica de luta"] },
      { nivel:11, bba:11, hab:["Aperfeiçoamento, meditação (1 hora), rajada de golpes aprimorada"] },
      { nivel:12, bba:12, hab:["Dano desarmado (2d6), movimento rápido +12m"] },
      { nivel:13, bba:13, hab:["Aperfeiçoamento"] },
      { nivel:14, bba:14, hab:["Movimento ágil +15, técnica de luta"] },
      { nivel:15, bba:15, hab:["Aperfeiçoamento, movimento rápido +15m, sexto sentido +3"] },
      { nivel:16, bba:16, hab:["Ataque chi (RD 15), dano desarmado (2d8)"] },
      { nivel:17, bba:17, hab:["Aperfeiçoamento, meditação (30 minutos)"] },
      { nivel:18, bba:18, hab:["Movimento rápido +18m, técnica de luta"] },
      { nivel:19, bba:19, hab:["Aperfeiçoamento, movimento ágil +20"] },
      { nivel:20, bba:20, hab:["Autoperfeição, dano desarmado (2d10), sexto sentido +4"] },
    ],
    habilidades: {
      "Dano Desarmado": "Monges são mestres do combate desarmado. Dano aumenta: 1d6 (1º), 1d8 (4º), 1d10 (8º), 2d6 (12º), 2d8 (16º), 2d10 (20º).",
      "Rajada de Golpes": "Ao atacar com armas de monge, pode fazer um ataque adicional. Todos os ataques sofrem −2. Pode gastar 1 PM para usar sem penalidade. A partir do 11º nível, não sofre mais a penalidade de −2 e pode gastar 1 PM para ganhar um segundo ataque adicional.",
      "Sexto Sentido": "Bônus na CA e em testes de Reflexos igual ao bônus de Sabedoria (mínimo +1). No 5º nível, e a cada 5 níveis, +1 adicional.",
      "Técnica de Luta": "No 1º nível (e nos 2º, 6º, 10º, 14º e 18º), recebe um talento de combate.",
      "Evasão": "No 2º nível, ao sofrer ataque que permite teste de Reflexos para reduzir dano à metade, você não sofre dano algum se for bem-sucedido. No 9º nível aprimorada: sofre apenas metade mesmo se falhar.",
      "Movimento Rápido": "No 3º nível +3m; 6º +6m; 9º +9m; 12º +12m; 15º +15m; 18º +18m.",
      "Ataque Chi": "No 4º nível, seus ataques desarmados superam RD 5. No 10º superam RD 10, no 16º superam RD 15.",
      "Movimento Ágil": "No 4º nível, +5 em testes de Acrobacia para se mover sem provocar ataques de oportunidade. Aumenta no 9º (+10), 14º (+15), 19º (+20).",
      "Meditação": "No 5º nível, para cada 2 horas de meditação recupera 2 PV e 1 PM por nível. Reduz para 1 hora no 11º e 30 minutos no 17º.",
      "Integridade Corporal": "No 7º nível, é imune a doenças e venenos.",
      "Aperfeiçoamento": "No 11º nível (e 13º, 15º, 17º, 19º), recebe um aperfeiçoamento: +2 em um atributo, ou uma habilidade especial de monge.",
      "Autoperfeição": "No 20º nível, recebe um aperfeiçoamento e atinge a perfeição corporal e espiritual.",
    }
  },

  ninja: {
    label: "Ninja", icon: "🌑", img: "assets/images/classes/Ninja.png",
    desc: "Assassino e espião furtivo, com um arsenal de poderes misteriosos.",
    honra: "−4",
    nivel_inicial: { "Esquiva Engenhosa":1,"Hierarquia do Clã":1,"Passo do Ninja":1,"Evasão":2,"Dano Desarmado":3,"Sentir Armadilhas":3,"Truques Ninjas":3,"Esquiva Sobrenatural":4,"Destemido":5,"Golpe Ninja":5,"Letalidade":9,"Demônio Ninja":20 },
    pv_base: 12, pv_nivel: 3,
    pm_base: 5,  pm_nivel: 3,
    pericias_treinadas: "6 + modificador de Inteligência",
    pericias_classe: "Acrobacia (Des), Atletismo (For), Atuação (Car), Cavalgar (Des), Cura (Sab), Enganação (Car), Furtividade (Des), Identificar Magia (Int), Iniciativa (Des), Intimidação (Car), Ladinagem (Des), Obter Informação (Car), Ofício (Int), Percepção (Sab), Sobrevivência (Sab).",
    talentos_iniciais: "Usar Armas (simples e ninja-to), Usar Arma Exótica (escolha quatro entre chicote, corrente, granada, jitte, kusari-gama, leque, neko-te, nunchaku, rede, sai, shuriken, tonfa), Reflexos Rápidos, Vontade de Ferro, Ataque Desarmado Aprimorado.",
    tabela: [
      { nivel:1,  bba:0,  hab:["Esquiva engenhosa, hierarquia do clã, passo do ninja (+5/+3m)"] },
      { nivel:2,  bba:1,  hab:["Evasão"] },
      { nivel:3,  bba:2,  hab:["Dano desarmado (1d6), sentir armadilhas +1, truques ninjas"] },
      { nivel:4,  bba:3,  hab:["Esquiva sobrenatural"] },
      { nivel:5,  bba:3,  hab:["Destemido, esquiva engenhosa +1, golpe ninja"] },
      { nivel:6,  bba:4,  hab:["Sentir armadilhas +2"] },
      { nivel:7,  bba:5,  hab:["Passo do ninja (+10/+6m)"] },
      { nivel:8,  bba:6,  hab:["Dano desarmado (1d8), esquiva sobrenatural aprimorada"] },
      { nivel:9,  bba:6,  hab:["Letalidade (multiplicador), sentir armadilhas +3"] },
      { nivel:10, bba:7,  hab:["Esquiva engenhosa +2, truques ninjas (−1 PM)"] },
      { nivel:11, bba:8,  hab:["Truques ninjas (Jutsu Acelerado)"] },
      { nivel:12, bba:9,  hab:["Evasão aprimorada, sentir armadilhas +4"] },
      { nivel:13, bba:9,  hab:["Dano desarmado (1d10)"] },
      { nivel:14, bba:10, hab:["Passo do ninja (+15/+9m)"] },
      { nivel:15, bba:11, hab:["Esquiva engenhosa +3, sentir armadilhas +5"] },
      { nivel:16, bba:12, hab:["Letalidade (margem de ameaça)"] },
      { nivel:17, bba:12, hab:["Truques ninjas (−3 PM)"] },
      { nivel:18, bba:13, hab:["Dano desarmado (2d6), sentir armadilhas +6"] },
      { nivel:19, bba:14, hab:["Truques ninjas (Jutsu Acelerado gratuito)"] },
      { nivel:20, bba:15, hab:["Demônio ninja, esquiva engenhosa +4"] },
    ],
    habilidades: {
      "Esquiva Engenhosa": "Soma o bônus de Inteligência à CA e a testes de Reflexos (mínimo +1). No 5º nível e a cada 5 níveis, +1 adicional ao bônus.",
      "Hierarquia do Clã": "Tem autoridade sobre ninjas de nível inferior. Pode gastar 1 PM para que subordinados realizem tarefa simples (CD = nível) ou 2 PM para tarefas difíceis (CD = nível + 5).",
      "Passo do Ninja": "No 1º nível, +5 em Acrobacia e Furtividade, +3m de deslocamento. No 7º aumenta para +10/+6m. No 14º para +15/+9m.",
      "Evasão": "No 2º nível, sem dano se bem-sucedido em Reflexos. No 12º aprimorada: metade do dano mesmo falhando.",
      "Dano Desarmado": "No 3º nível 1d6; no 8º 1d8; no 13º 1d10; no 18º 2d6.",
      "Sentir Armadilhas": "No 3º nível, +1 em Reflexos e CA contra armadilhas. Aumenta +1 a cada 3 níveis.",
      "Truques Ninjas": "A partir do 3º nível, aprende e executa jutsus do descritor ninja pelo custo normal, independente de grau e chacras. No 10º nível, executa por −1 PM. No 11º recebe Jutsu Acelerado. No 17º executa por −3 PM. No 19º Jutsu Acelerado custa 0 PM adicional.",
      "Esquiva Sobrenatural": "No 4º nível, nunca fica surpreendido. No 8º aprimorada: não pode ser flanqueado.",
      "Destemido": "No 5º nível, é imune a medo.",
      "Golpe Ninja": "No 5º nível, ao atacar desarmado ou com arma ninja, pode gastar 1 PM para +4 na jogada de ataque. Se acertar, causa +1 dano por nível e o ninja recupera 2 PM.",
      "Letalidade": "No 9º nível, multiplicador de crítico de todos os ataques aumenta em +1. No 16º, todos os ataques recebem +1 na margem de ameaça.",
      "Demônio Ninja": "No 20º nível, pode gastar 2 PM para causar o dano ou efeito de qualquer ataque que levaria o alvo a 0 PV — exceto ataques de outros ninjas.",
    }
  },

  onimusha: {
    label: "Onimusha", icon: "👹", img: "assets/images/classes/Onimusha.png",
    desc: "Caçador de monstros que adquire poderes aberrantes.",
    honra: "−2",
    nivel_inicial: { "Caminhos Aberrantes":1,"Faro para Monstros":1,"Potência Aberrante":3,"Devorador de Almas":5,"Inimigo de Monstros":7,"Momento de Tormenta":8,"Resistente a Monstros":9,"Matador":11,"Matador Supremo":20 },
    pv_base: 20, pv_nivel: 5,
    pm_base: 4,  pm_nivel: 2,
    pericias_treinadas: "4 + modificador de Inteligência",
    pericias_classe: "Adestrar Animais (Car), Atletismo (For), Cavalgar (Des), Conhecimento (Int), Cura (Sab), Furtividade (Des), Iniciativa (Des), Ofício (Int), Percepção (Sab), Sobrevivência (Sab).",
    talentos_iniciais: "Usar Armaduras (leves, médias), Usar Armas (simples, marciais), Fortitude Maior, Reflexos Rápidos, Rastrear.",
    tabela: [
      { nivel:1,  bba:1,  hab:["Caminhos aberrantes, faro para monstros"] },
      { nivel:2,  bba:2,  hab:["Caminhos aberrantes"] },
      { nivel:3,  bba:3,  hab:["Potência aberrante"] },
      { nivel:4,  bba:4,  hab:["Caminhos aberrantes"] },
      { nivel:5,  bba:5,  hab:["Devorador de almas (1 PM)"] },
      { nivel:6,  bba:6,  hab:["Caminhos aberrantes"] },
      { nivel:7,  bba:7,  hab:["Inimigo de monstros +2"] },
      { nivel:8,  bba:8,  hab:["Caminhos aberrantes, momento de Tormenta"] },
      { nivel:9,  bba:9,  hab:["Resistente a monstros +2"] },
      { nivel:10, bba:10, hab:["Caminhos aberrantes"] },
      { nivel:11, bba:11, hab:["Matador"] },
      { nivel:12, bba:12, hab:["Caminhos aberrantes"] },
      { nivel:13, bba:13, hab:["Inimigo de monstros +4"] },
      { nivel:14, bba:14, hab:["Caminhos aberrantes"] },
      { nivel:15, bba:15, hab:["Devorador de almas (2 PM)"] },
      { nivel:16, bba:16, hab:["Caminhos aberrantes"] },
      { nivel:17, bba:17, hab:["Resistente a monstros +4"] },
      { nivel:18, bba:18, hab:["Caminhos aberrantes"] },
      { nivel:19, bba:19, hab:["Inimigo de monstros +8"] },
      { nivel:20, bba:20, hab:["Caminhos aberrantes, matador supremo"] },
    ],
    habilidades: {
      "Caminhos Aberrantes": "No 1º nível, e a cada 2 níveis seguintes, escolhe uma habilidade entre: Arma simbionte, Armadura simbionte, Companheiro aberrante (Animal Feroz, Animal Guardião ou Animal de Montaria) ou Talento potente. Cada escolha repetida evolui a habilidade.",
      "Faro para Monstros": "No 1º nível, detecta automaticamente a presença de criaturas do tipo monstro a até 9m (sem direção/localização).",
      "Potência Aberrante": "No 3º nível, pode gastar 2 PM (ação livre) para elevar temporariamente suas habilidades: Arma potente (+1 ataque/dano, até +5), Armadura potente (+1 CA/resistências, até +5) ou Companheiro potente (+1 dano/CA).",
      "Devorador de Almas": "No 5º nível, ao reduzir uma criatura a 0 PV ou menos (até 9m), recupera 1 PM. Se o ND da criatura for muito baixo, não recupera. No 15º nível, recupera 2 PM.",
      "Inimigo de Monstros": "No 7º nível, +2 em jogadas de dano e testes de perícia feitos contra monstros. Aumenta para +4 no 13º e +8 no 19º nível.",
      "Momento de Tormenta": "No 8º nível, pode gastar uma ação de movimento e 6 PM para criar uma pequena área de Tormenta centrada nele mesmo (duração de cena, 9m de raio). A cada rodada, no início dos turnos, um efeito aleatório: Chuva ácida (4d4 de ácido), Neblina venenosa (1d6 de Constituição) ou Tempestade elétrica (5d10 de eletricidade).",
      "Resistente a Monstros": "No 9º nível, +2 em CA e testes de resistência contra ataques e poderes de monstros. Aumenta para +4 no 17º nível.",
      "Matador": "No 11º nível, os ataques e jutsus do onimusha ignoram qualquer redução de dano ou resistência a energia de monstros.",
      "Matador Supremo": "No 20º nível, todos os acertos críticos do onimusha contra monstros têm o multiplicador de crítico aumentado em +2. Ignora imunidade a acertos críticos de qualquer monstro com ND menor que o nível do onimusha.",
    }
  },

  samurai: {
    label: "Samurai", icon: "🗡️", img: "assets/images/classes/Samurai.png",
    desc: "Honrado guerreiro aristocrata, portador de espadas ancestrais.",
    honra: "+2",
    nivel_inicial: { "Devoto de Lin-Wu":1,"Detectar Desonra":1,"Espadas Ancestrais":1,"Estilo de Combate":2,"Grito de Kiai":2,"Técnica de Luta":4,"Poder Concedido":5,"Olhar Assustador":7,"Domínio do Estilo de Combate":11,"Honra Absoluta":14,"Honra Suprema":20 },
    pv_base: 20, pv_nivel: 5,
    pm_base: 4,  pm_nivel: 2,
    pericias_treinadas: "4 + modificador de Inteligência",
    pericias_classe: "Acrobacia (Des), Adestrar Animais (Car), Atletismo (For), Atuação (Car), Cavalgar (Des), Conhecimento (Int), Diplomacia (Car), Iniciativa (Des), Intimidação (Car), Intuição (Sab), Ofício (Int), Percepção (Sab).",
    talentos_iniciais: "Usar Armaduras (leves, médias e pesadas), Usar Armas (simples e marciais), Fortitude Maior, Vontade de Ferro.",
    tabela: [
      { nivel:1,  bba:1,  hab:["Devoto de Lin-Wu, detectar desonra, espadas ancestrais +1"] },
      { nivel:2,  bba:2,  hab:["Estilo de combate, grito de kiai"] },
      { nivel:3,  bba:3,  hab:["Espadas ancestrais +2"] },
      { nivel:4,  bba:4,  hab:["Técnica de luta"] },
      { nivel:5,  bba:5,  hab:["Espadas ancestrais +3, poder concedido"] },
      { nivel:6,  bba:6,  hab:["Estilo de combate aprimorado"] },
      { nivel:7,  bba:7,  hab:["Espadas ancestrais +4, olhar assustador"] },
      { nivel:8,  bba:8,  hab:["Técnica de luta"] },
      { nivel:9,  bba:9,  hab:["Espadas ancestrais +5"] },
      { nivel:10, bba:10, hab:["Grito de kiai aprimorado, poder concedido"] },
      { nivel:11, bba:11, hab:["Domínio do estilo de combate, espadas ancestrais +6"] },
      { nivel:12, bba:12, hab:["Técnica de luta"] },
      { nivel:13, bba:13, hab:["Espadas ancestrais +7"] },
      { nivel:14, bba:14, hab:["Honra absoluta, olhar assustador em massa"] },
      { nivel:15, bba:15, hab:["Espadas ancestrais +8, poder concedido"] },
      { nivel:16, bba:16, hab:["Poder concedido, técnica de luta"] },
      { nivel:17, bba:17, hab:["Espadas ancestrais +9"] },
      { nivel:18, bba:18, hab:["Grito de kiai maior"] },
      { nivel:19, bba:19, hab:["Espadas ancestrais +10"] },
      { nivel:20, bba:20, hab:["Honra suprema, poder concedido, técnica de luta"] },
    ],
    habilidades: {
      "Devoto de Lin-Wu": "Recebe o talento Devoto de Lin-Wu. Devotar-se a outra religião faz perder este talento e seus poderes.",
      "Detectar Desonra": "Recebe Detectar Desonra como talento adicional.",
      "Espadas Ancestrais": "No 1º nível, recebe uma katana e uma wakizashi (daisho) sem custo. A cada 2 níveis (1º, 3º, 5º...), uma das armas à sua escolha recebe bônus mágico +1 acumulativo. Nas mãos de outro, as armas se comportam como peças comuns.",
      "Estilo de Combate": "No 2º nível, escolhe iaijutsu, kyudo (arquearia) ou nitoichi (duas armas). Confere talentos específicos. No 6º aprimorado: confere talentos adicionais de acordo com o estilo.",
      "Grito de Kiai": "No 2º nível, ação livre, gasta 1 PM: +2 nas jogadas de ataque e dano por uma rodada. No 10º aprimorado: +4. No 18º maior: +8. Ao 10º nível, também pode aprender Conhecimento de Jutsus para jutsus com 'kiai' no nome.",
      "Técnica de Luta": "No 4º nível, e a cada 4 níveis seguintes, recebe um talento de combate.",
      "Poder Concedido": "No 5º nível (e 10º, 15º, 16º, 20º), recebe um talento de poder concedido de Lin-Wu, à sua escolha.",
      "Olhar Assustador": "No 7º nível, aprende o jutsu face horripilante (sem violar honra). No 14º nível, ao executar o jutsu, pode afetar qualquer quantidade de alvos dentro do alcance.",
      "Domínio do Estilo de Combate": "No 11º nível, recebe talentos adicionais conforme o estilo escolhido.",
      "Honra Absoluta": "A partir do 14º nível, pode usar Honra como reserva de força uma vez por cena.",
      "Honra Suprema": "No 20º nível, é o mais terrível inimigo daqueles sem honra. Ataques contra adversários desonrados (Honra 9 ou menos) causam +4d6 de dano de vácuo adicional, ataques contra sórdidos (Honra 5 ou menos) também são acertos críticos e contra desumanados (Honra 0) são golpes de misericórdia.",
    }
  },

  shinkan: {
    label: "Shinkan", icon: "👻", img: "assets/images/classes/Shinkan.png",
    desc: "Mestre de jutsus ligado ao mundo dos espíritos.",
    honra: "+0",
    nivel_inicial: { "Aprendiz dos Espíritos":1,"Canalizar Energia":1,"Devoto do Bushintau":1,"Conhecimento de Jutsus":2,"Raio Espiritual":2,"Discípulo dos Espíritos":3,"Lições Espirituais":4,"Meditação":7,"Iniciado dos Espíritos":6,"Adepto dos Espíritos":10,"Mestre dos Espíritos":15,"União Espiritual":20 },
    pv_base: 12, pv_nivel: 3,
    pm_base: 6,  pm_nivel: 4,
    pericias_treinadas: "4 + modificador de Inteligência",
    pericias_classe: "Adestrar Animais (Car), Atletismo (For), Cavalgar (Des), Conhecimento (Int), Cura (Sab), Diplomacia (Car), Enganação (Car), Identificar Magia (Int), Intuição (Sab), Ofício (Int), Percepção (Sab), Sobrevivência (Sab).",
    talentos_iniciais: "Usar Armaduras (leves), Usar Armas (simples), Vontade de Ferro.",
    tabela: [
      { nivel:1,  bba:0,  hab:["Aprendiz dos espíritos, canalizar energia 1d6, devoto do Bushintau"] },
      { nivel:2,  bba:1,  hab:["Conhecimento de jutsus, raio espiritual (1d4)"] },
      { nivel:3,  bba:1,  hab:["Discípulo dos espíritos, canalizar energia 2d6"] },
      { nivel:4,  bba:2,  hab:["Conhecimento de jutsus, lições espirituais"] },
      { nivel:5,  bba:2,  hab:["Canalizar energia 3d6, raio espiritual (1d6)"] },
      { nivel:6,  bba:3,  hab:["Iniciado dos espíritos, conhecimento de jutsus"] },
      { nivel:7,  bba:3,  hab:["Canalizar energia 4d6, meditação (2 horas)"] },
      { nivel:8,  bba:4,  hab:["Conhecimento de jutsus, lições espirituais"] },
      { nivel:9,  bba:4,  hab:["Canalizar energia 5d6, raio espiritual (1d8)"] },
      { nivel:10, bba:5,  hab:["Adepto dos espíritos, conhecimento de jutsus"] },
      { nivel:11, bba:5,  hab:["Canalizar energia 6d6"] },
      { nivel:12, bba:6,  hab:["Conhecimento de jutsus, lições espirituais"] },
      { nivel:13, bba:6,  hab:["Canalizar energia 7d6, meditação (1 hora), raio espiritual (1d10, 30m)"] },
      { nivel:14, bba:7,  hab:["Conhecimento de jutsus"] },
      { nivel:15, bba:7,  hab:["Canalizar energia 8d6, mestre dos espíritos"] },
      { nivel:16, bba:8,  hab:["Conhecimento de jutsus, lições espirituais"] },
      { nivel:17, bba:8,  hab:["Canalizar energia 9d6, raio espiritual (1d12)"] },
      { nivel:18, bba:9,  hab:["Conhecimento de jutsus"] },
      { nivel:19, bba:9,  hab:["Canalizar energia 10d6, meditação (30 minutos)"] },
      { nivel:20, bba:10, hab:["Conhecimento de jutsus, lições espirituais, união espiritual"] },
    ],
    habilidades: {
      "Aprendiz dos Espíritos": "Aprende jutsus básicos de Sabedoria em quantidade igual ao bônus de Sabedoria (mínimo +1). Pode aprender jutsus com 'espírito' ou 'ancestrais' no nome de qualquer grau.",
      "Canalizar Energia": "Ação padrão, afeta todas as criaturas a até 9m (inclusive você): luz cura 1d6 PV (shiryou e oni com Honra ≤5 sofrem 1d6 de luz); trevas curam 1d6 PV de outras criaturas (escolher trevas é violação de honra moderada). No 5º nível e a cada 4 seguintes, o dado aumenta +1d6. Custo: 1 PM por dado.",
      "Devoto do Bushintau": "Recebe o talento Devoto do Bushintau. Devotar-se a Lin-Wu ou à Família Celestial faz perder este talento e seus poderes.",
      "Conhecimento de Jutsus": "No 2º nível, aprende dois novos jutsus de grau básico. No 4º nível e a cada 2 níveis seguintes, aprende dois novos jutsus de qualquer grau e chacra.",
      "Raio Espiritual": "Pode disparar um raio de energia a até 9m. Acerto cura ou causa 1d4 (2º), 1d6 (5º), 1d8 (9º), 1d10 (13º) ou 1d12 (17º) pontos. No 13º o alcance vai a 30m. Fora de perigo custa 1 PM adicional.",
      "Discípulo dos Espíritos": "No 3º nível, pode aprender jutsus de Sabedoria de grau mediano. Soma o bônus de Sabedoria ao total de PM.",
      "Lições Espirituais": "No 4º nível, recebe um talento de poder concedido do Bushintau ou um talento de jutsu.",
      "Meditação": "No 7º nível, para cada 2 horas de meditação recupera 2 PV e 1 PM por nível. Reduz para 1 hora no 13º e 30 minutos no 19º.",
      "Iniciado dos Espíritos": "No 6º nível, pode aprender jutsus de Sabedoria de grau avançado. Soma novamente o bônus de Sabedoria ao total de PM.",
      "Adepto dos Espíritos": "No 10º nível, pode aprender jutsus de Sabedoria de grau sublime. Soma novamente o bônus de Sabedoria ao total de PM.",
      "Mestre dos Espíritos": "No 15º nível, pode aprender jutsus de Sabedoria de grau lendário. Soma novamente o bônus de Sabedoria ao total de PM.",
      "União Espiritual": "No 20º nível, fica permanentemente sob o efeito do jutsu forma espiritual e pode executar qualquer jutsu nessa forma. Não pode ser anulado.",
    }
  },

  shugenja: {
    label: "Shugenja", icon: "🌸", img: "assets/images/classes/Shugenja.png",
    desc: "Servo divino de Lin-Wu e sua Família Celestial.",
    honra: "+2",
    nivel_inicial: { "Aprendiz Celestial":1,"Defesa da Honra":1,"Devoto":1,"Conhecimento de Jutsus":2,"Orientação":2,"Discípulo Celestial":3,"Poder Concedido":4,"Iniciado Celestial":6,"Fortaleza da Honra":7,"Adepto Celestial":10,"Mestre Celestial":15,"Escolhido Celestial":20 },
    pv_base: 16, pv_nivel: 4,
    pm_base: 6,  pm_nivel: 4,
    pericias_treinadas: "4 + modificador de Inteligência",
    pericias_classe: "Atletismo (For), Atuação (Car), Cavalgar (Des), Conhecimento (Int), Cura (Sab), Diplomacia (Car), Identificar Magia (Int), Iniciativa (Des), Intuição (Sab), Ofício (Int), Percepção (Sab).",
    talentos_iniciais: "Usar Armas (simples), Fortitude Maior, Vontade de Ferro.",
    tabela: [
      { nivel:1,  bba:0,  hab:["Aprendiz celestial, defesa da honra, devoto"] },
      { nivel:2,  bba:1,  hab:["Conhecimento de jutsus, orientação"] },
      { nivel:3,  bba:2,  hab:["Discípulo celestial"] },
      { nivel:4,  bba:3,  hab:["Conhecimento de jutsus, poder concedido"] },
      { nivel:5,  bba:3,  hab:["Orientação, defesa da honra +1"] },
      { nivel:6,  bba:4,  hab:["Iniciado celestial, conhecimento de jutsus"] },
      { nivel:7,  bba:5,  hab:["Fortaleza da honra"] },
      { nivel:8,  bba:6,  hab:["Conhecimento de jutsus, poder concedido"] },
      { nivel:9,  bba:6,  hab:["Defesa da honra aprimorado"] },
      { nivel:10, bba:7,  hab:["Adepto celestial, conhecimento de jutsus, defesa da honra +2"] },
      { nivel:11, bba:8,  hab:["Orientação"] },
      { nivel:12, bba:9,  hab:["Conhecimento de jutsus, poder concedido"] },
      { nivel:13, bba:9,  hab:["Fortaleza da honra aprimorada"] },
      { nivel:14, bba:10, hab:["Conhecimento de jutsus, orientação"] },
      { nivel:15, bba:11, hab:["Mestre celestial, defesa da honra +3"] },
      { nivel:16, bba:12, hab:["Conhecimento de jutsus, poder concedido"] },
      { nivel:17, bba:12, hab:["Orientação"] },
      { nivel:18, bba:13, hab:["Conhecimento de jutsus"] },
      { nivel:19, bba:14, hab:["Fortaleza da honra maior"] },
      { nivel:20, bba:15, hab:["Conhecimento de jutsus, escolhido celestial, defesa da honra +4, orientação, poder concedido"] },
    ],
    habilidades: {
      "Aprendiz Celestial": "Aprende jutsus básicos de Sabedoria em quantidade igual ao bônus de Sabedoria (mínimo +1). Pode aprender jutsus com 'celestial' ou 'ancestral' no nome de qualquer grau.",
      "Defesa da Honra": "Adiciona o bônus de Honra à CA e a testes de Reflexos (mínimo +0). No 5º nível e a cada 5 níveis, +1 adicional. A partir do 9º, pode gastar 1 PM como ação livre para receber redução de dano igual ao bônus de Honra por 1 rodada.",
      "Devoto": "Escolhe entre Devoto de Lin-Wu ou Devoto da Família Celestial. Devotar-se à outra religião faz perder este talento e seus poderes.",
      "Conhecimento de Jutsus": "No 2º nível, aprende dois novos jutsus de grau básico. No 4º nível e a cada 2 níveis, aprende dois novos jutsus de qualquer grau.",
      "Orientação": "No 2º nível, pode aconselhar seus nakamas com sabedoria. Escolhe um efeito diferente a cada novo nível em que recebe esta habilidade. Afeta criaturas Int 3+ e honradas (Hon 10+) que possam vê-lo e ouvi-lo.",
      "Discípulo Celestial": "No 3º nível, pode aprender e executar jutsus de Sabedoria de grau mediano. Pode somar o bônus de Sabedoria ou de Honra ao total de PM.",
      "Poder Concedido": "No 4º nível (e 8º, 12º, 16º, 20º), recebe um talento de poder concedido da religião correspondente.",
      "Iniciado Celestial": "No 6º nível, pode aprender e executar jutsus de Sabedoria de grau avançado. Soma o bônus de Sabedoria ou Honra ao total de PM novamente.",
      "Fortaleza da Honra": "No 7º nível, você e suas criaturas escolhidas a até 9m recebem resistência 5 a energia (duração de cena, gasto 6 PM). No 13º aumenta para 10, no 19º para 15. Criaturas honradas (Hon 16+) recebem o dobro do valor.",
      "Adepto Celestial": "No 10º nível, pode aprender e executar jutsus de Sabedoria de grau sublime.",
      "Mestre Celestial": "No 15º nível, pode aprender e executar jutsus de Sabedoria de grau lendário.",
      "Escolhido Celestial": "No 20º nível, pode reduzir o custo em PM de qualquer jutsu em valor igual ao maior entre o bônus de Sabedoria e de Honra (mínimo 1 PM). Fica imune a efeitos de encantamento e ilusão.",
    }
  },

  wujen: {
    label: "Wu-jen", icon: "🌀", img: "assets/images/classes/Wu-Jen.png",
    desc: "Conjurador caótico e rebelde.",
    honra: "−1",
    nivel_inicial: { "Aprendiz da Mente":1,"Percepção Elemental":1,"Raio Elemental":1,"Conhecimento de Jutsus":2,"Segredos dos Chacras":2,"Discípulo da Mente":3,"Estudos Caóticos":5,"Iniciado da Mente":6,"Segredos da Anulação":9,"Adepto da Mente":10,"Mestre da Mente":15,"Caos Elemental":20 },
    pv_base: 8, pv_nivel: 2,
    pm_base: 6,  pm_nivel: 4,
    pericias_treinadas: "2 + modificador de Inteligência",
    pericias_classe: "Conhecimento (Int), Enganação (Car), Identificar Magia (Int), Intimidação (Car), Intuição (Sab), Ofício (Int), Percepção (Sab), Sobrevivência (Sab).",
    talentos_iniciais: "Usar Armas (simples), Vontade de Ferro.",
    tabela: [
      { nivel:1,  bba:0,  hab:["Aprendiz da mente, percepção elemental, raio elemental"] },
      { nivel:2,  bba:1,  hab:["Conhecimento de jutsus, segredos dos chacras"] },
      { nivel:3,  bba:1,  hab:["Discípulo da mente"] },
      { nivel:4,  bba:2,  hab:["Conhecimento de jutsus, segredos dos chacras"] },
      { nivel:5,  bba:2,  hab:["Estudos caóticos, raio elemental (1d6)"] },
      { nivel:6,  bba:3,  hab:["Iniciado da mente, conhecimento de jutsus"] },
      { nivel:7,  bba:3,  hab:["Segredos dos chacras"] },
      { nivel:8,  bba:4,  hab:["Conhecimento de jutsus"] },
      { nivel:9,  bba:4,  hab:["Raio elemental (1d8), segredos dos chacras"] },
      { nivel:10, bba:5,  hab:["Adepto da mente, conhecimento de jutsus, estudos caóticos"] },
      { nivel:11, bba:5,  hab:["Segredos dos chacras"] },
      { nivel:12, bba:6,  hab:["Conhecimento de jutsus"] },
      { nivel:13, bba:6,  hab:["Raio elemental (1d10, 30m)"] },
      { nivel:14, bba:7,  hab:["Conhecimento de jutsus"] },
      { nivel:15, bba:7,  hab:["Estudos caóticos, mestre da mente"] },
      { nivel:16, bba:8,  hab:["Conhecimento de jutsus, segredos dos chacras"] },
      { nivel:17, bba:8,  hab:["Raio elemental (1d12, múltiplos raios)"] },
      { nivel:18, bba:9,  hab:["Conhecimento de jutsus"] },
      { nivel:19, bba:9,  hab:["Segredos dos chacras"] },
      { nivel:20, bba:10, hab:["Caos elemental, conhecimento de jutsus, estudos caóticos"] },
    ],
    habilidades: {
      "Aprendiz da Mente": "Abre o chacra da mente: aprende e executa jutsus básicos de Inteligência. Soma o bônus de Int ao total de PM. Aprende quatro jutsus básicos de Inteligência. Também pode aprender jutsus com 'mandala' no nome de qualquer grau.",
      "Percepção Elemental": "Ação padrão de concentração: detecta objetos ou fontes de um elemento. 1 rodada: presença e quantidade. 2 rodadas: tamanho. 3 rodadas: localização exata (mesmo escondidas). Alcance de 9m.",
      "Raio Elemental": "Ataque de toque à distância (até 9m): 1d4 de dano elemental (ácido, eletricidade, fogo, frio ou vento, escolhido no momento). No 5º nível aumenta para 1d6. No 9º 1d8. No 13º 1d10 e alcance 30m. No 17º 1d12 e pode disparar múltiplos raios (um por modificador de Int, com mesma ação, gastando 1 PM extra por raio adicional).",
      "Conhecimento de Jutsus": "No 2º nível, aprende três novos jutsus de grau básico. No 4º e a cada 2 níveis, aprende três novos jutsus de qualquer grau.",
      "Segredos dos Chacras": "No 2º nível, recebe o talento Abrir Chacra. No 4º, 7º, 11º, 16º e 19º, recebe Abrir Chacra para outro chacra. Se já tiver todos abertos, recebe Chacra Intermediário para um chacra de grau básico.",
      "Discípulo da Mente": "No 3º nível, pode aprender e executar jutsus de Int de grau mediano. Soma novamente o bônus de Int ao total de PM.",
      "Estudos Caóticos": "No 5º nível, recebe um talento de jutsu. No 10º e a cada 5 níveis, recebe outro talento de jutsu.",
      "Iniciado da Mente": "No 6º nível, pode aprender e executar jutsus de Int de grau avançado. Soma novamente o bônus de Int ao total de PM.",
      "Segredos da Anulação": "A partir do 9º nível, pode usar uma reação uma vez por rodada para anular um jutsu em execução: testa Identificar Magia; se bem-sucedido, gasta a mesma quantidade de PM do oponente e faz teste oposto de Vontade para anular o jutsu.",
      "Adepto da Mente": "No 10º nível, pode aprender e executar jutsus de Int de grau sublime. Soma novamente o bônus de Int ao total de PM.",
      "Mestre da Mente": "No 15º nível, pode aprender e executar jutsus de Int de grau lendário. Soma novamente o bônus de Int ao total de PM.",
      "Caos Elemental": "No 20º nível, ao executar qualquer jutsu com descritor elemental, pode rolar 3d4 e pagar esse valor em PM: o dano ou efeito do jutsu não pode ser reduzido de forma alguma por resistências, imunidades ou quaisquer habilidades.",
    }
  },

  yakuza: {
    label: "Yakuza", icon: "🎴", img: "assets/images/classes/Yakuza.png",
    desc: "Fora-da-lei cheio de truques e contatos.",
    honra: "−2",
    nivel_inicial: { "Ataque Furtivo":1,"Hierarquia do Kumi":1,"Rede de Informantes":1,"Evasão":2,"Extorsão":2,"Recursos Escusos":3,"Esquiva Sobrenatural":5,"Capangas":6,"Vingança":7,"Mente Escorregadia":9,"Vingança Final":20 },
    pv_base: 12, pv_nivel: 3,
    pm_base: 4,  pm_nivel: 2,
    pericias_treinadas: "8 + modificador de Inteligência",
    pericias_classe: "Acrobacia (Des), Atletismo (For), Atuação (Car), Cavalgar (Des), Conhecimento (Int), Diplomacia (Car), Enganação (Car), Furtividade (Des), Identificar Magia (Int), Iniciativa (Des), Intimidação (Car), Intuição (Sab), Ladinagem (Des), Obter Informação (Car), Ofício (Int), Percepção (Sab).",
    talentos_iniciais: "Usar Armaduras (leves), Usar Armas (simples), Reflexos Rápidos.",
    tabela: [
      { nivel:1,  bba:0,  hab:["Ataque furtivo +1d6, hierarquia do kumi, rede de informantes"] },
      { nivel:2,  bba:1,  hab:["Evasão, extorsão"] },
      { nivel:3,  bba:2,  hab:["Recursos escusos"] },
      { nivel:4,  bba:3,  hab:["Ataque furtivo +2d6"] },
      { nivel:5,  bba:3,  hab:["Esquiva sobrenatural, extorsão"] },
      { nivel:6,  bba:4,  hab:["Capangas"] },
      { nivel:7,  bba:5,  hab:["Vingança, ataque furtivo +3d6"] },
      { nivel:8,  bba:6,  hab:["Extorsão"] },
      { nivel:9,  bba:6,  hab:["Mente escorregadia"] },
      { nivel:10, bba:7,  hab:["Esquiva sobrenatural aprimorada, ataque furtivo +4d6"] },
      { nivel:11, bba:8,  hab:["Extorsão"] },
      { nivel:12, bba:9,  hab:["Capangas, evasão aprimorada"] },
      { nivel:13, bba:9,  hab:["Ataque furtivo +5d6"] },
      { nivel:14, bba:10, hab:["Extorsão, vingança aprimorada"] },
      { nivel:15, bba:11, hab:["Mente escorregadia aprimorada"] },
      { nivel:16, bba:12, hab:["Ataque furtivo +6d6"] },
      { nivel:17, bba:12, hab:["Extorsão"] },
      { nivel:18, bba:13, hab:["Capangas"] },
      { nivel:19, bba:14, hab:["Ataque furtivo +7d6"] },
      { nivel:20, bba:15, hab:["Vingança final, extorsão"] },
    ],
    habilidades: {
      "Ataque Furtivo": "Ao atingir alvo desprevenido ou flanqueado com ataque corpo-a-corpo (ou à distância até 9m), causa +1d6 de dano adicional. Aumenta +1d6 a cada 3 níveis (máximo +7d6 no 19º nível). Criaturas imunes a críticos também são imunes a ataques furtivos.",
      "Hierarquia do Kumi": "Tem autoridade sobre yakuzas de nível inferior. Gasta 1 PM para tarefas simples (CD = nível) ou 2 PM para difíceis (CD = nível + 5). Subordinados podem preparar terreno e aparecer para resolver problemas.",
      "Rede de Informantes": "Sempre faz testes de Conhecimento como se fosse treinado. Para Obter Informação, gasta apenas 1 hora (em vez de 1 dia), não precisa de dinheiro, e tem facilidade para convencer pessoas a responder.",
      "Evasão": "No 2º nível, sem dano se bem-sucedido em Reflexos. No 12º aprimorada: metade do dano mesmo falhando.",
      "Extorsão": "No 2º nível, e a cada 3 níveis seguintes, escolhe um efeito. Ação de movimento, gasta 1 PM. Afeta criaturas Int 3+ a até 9m, dura 1 rodada. Efeitos: Abalar, Apavorar, Ameaçar, Cabeça Baixa (+2/+4/+6 em testes de resistência), Dedo-Duro (+1d4/+1d6/+1d8 de dano a nakamas), Hora do Pagamento (paga PM em dobro para qualquer habilidade), Lutar outro dia (+3/+6/+9m deslocamento), Mão de Alface (−4/−6/−8 em perícia), Pede Desculpas (usa Voz de Lin-Wu em alvo já abalado).",
      "Recursos Escusos": "No 3º nível, pode acessar o mercado negro para obter itens (mundanos ou mágicos) de qualquer parte do mundo. Consome PM conforme o valor do item (2 PM até 1.000 ¥o; até 20 PM para 100.000 ¥o). Os PM ficam 'presos' até devolver o item ou pagar em dinheiro.",
      "Esquiva Sobrenatural": "No 5º nível, nunca fica surpreendido. No 10º aprimorada: não pode ser flanqueado.",
      "Capangas": "No 6º nível, adquire Liderança como talento bônus. No 12º pode escolher Liderança que não escolheu antes. No 18º recebe um segundo parceiro ou aumenta a dificuldade máxima das tarefas.",
      "Vingança": "No 7º nível, quando um nakama é reduzido a 0 PV, pode reagir (1 PM) para fazer um ataque furtivo imediato (corpo-a-corpo ou à distância até 9m). No 14º aprimorado: além do ataque imediato, pode fazer ataques furtivos contra o agressor até o fim da cena mesmo sem flanquear.",
      "Mente Escorregadia": "No 9º nível, ao falhar em teste de Vontade, pode repetir na próxima rodada (fica com o novo resultado, mesmo pior). No 15º, pode repetir em cada rodada subsequente até ser bem-sucedido.",
      "Vingança Final": "No 20º nível, quando um nakama é reduzido a 0 PV, pode gastar 6 PM: todos os ataques do yakuza e seus nakamas contra o agressor causam +4d6 de dano de vácuo adicional, podem causar morte instantânea (CD 28) e são considerados golpes de misericórdia até o fim da cena.",
    }
  },
};
